name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - ipympl
  - ipywidgets
  - partd
  - bokeh
  - dask
  - voila
  - voila-gridstack
  - voila-material
